apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: devfile-sample-dotnet60-basic-bwus
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: devfile-sample-dotnet60-basic-bwus
    app.kubernetes.io/part-of: component-annotation-dotnet-component
  name: devfile-sample-dotnet60-basic-bwus
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: devfile-dotnet-deploy
      app.kubernetes.io/instance: devfile-sample-dotnet60-basic-bwus
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: devfile-dotnet-deploy
        app.kubernetes.io/instance: devfile-sample-dotnet60-basic-bwus
    spec:
      containers:
      - image: quay.io/redhat-appstudio-qe/rs-demos-mymh-tenant/component-annotation-dotnet-component/devfile-sample-dotnet60-basic-bwus@sha256:9ddf8404ae0db7c99b50c41e8968a42bacf3c3734dd78eded727d04296cc4061
        imagePullPolicy: Always
        name: main
        ports:
        - containerPort: 8081
          name: http
          protocol: TCP
        resources:
          requests:
            cpu: 10m
            memory: 100Mi
status: {}
